rm(list=ls())
pos_words=read.csv("pos_words.csv",header = F)
neg_words=read.csv("neg_words.csv",header=F)
pos_words=as.character(pos_words$V1)
neg_words=as.character(neg_words$V1)
all_words=c(pos_words,neg_words)
library("tm")
as.vector(neg_words)
x=table(all_words)
x=as.data.frame(x)
x$all_words=as.character(x$all_words)
freq=cbind(names(x),as.integer(x))
library("wordcloud")
set.seed(130)
png("all_words.png", width=3,height=3, units='in', res=300)
wordcloud(words = x[,1], freq = x[,2], min.freq = 100,
          max.words=130, random.order=FALSE, scale = c(3.5,0.25), 
          colors=brewer.pal(8, "Dark2"))
dev.off()
